version: "3.9"
services:
  rsyslog:
    logging:
      options:
        max-size: "1000m"
        max-file: "2"
    image: ghcr.io/sekoia-io/sekoiaio-docker-concentrator:latest
    environment:
      - MEMORY_MESSAGES=100000
      - DISK_SPACE=32g
    ports:
      - "20516-20518:20516-20518"
    volumes:
      - ./intakes.yaml:/intakes.yaml
      - ./conf:/etc/rsyslog.d
      - ./rsyslog:/var/spool/rsyslog
